"""Added Game Password and Players

Revision ID: 77c8441d630c
Revises: 
Create Date: 2023-08-07 11:50:23.174202

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '77c8441d630c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
        batch_op.drop_column('description')
        batch_op.drop_column('status')

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('game_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('game_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('description', mysql.VARCHAR(length=200), nullable=True))
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
